name: ai_gis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy=2.3.0
  - pandas=2.3.1
  - rasterio=1.4.3
  - netcdf4=1.7.2
  - dask=2024.5.1
  - geopandas=1.1.1
  - ipython=8.24.0
  - rioxarray=0.19.0
  - ipykernel=6.29.4
  - datasets=3.6.0
  - huggingface_hub=0.34.4
  - tqdm=4.67.1
  - ipywidgets=8.1.7
  - seaborn=0.13.2
  - pip
  - pip:
      - torch
      - torchvision
